---
title: "Distribuição repasse ICMS"
author: "Otávio Alves"
date: "22/01/2021"
output:
  pdf_document: default
  html_document: default
---

## R Markdown

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r echo = T, results = 'hide'}
install.packages('ineq', repos="http://cran.us.r-project.org")
library(ineq)
install.packages('readxl', repos="http://cran.us.r-project.org")
library(readxl)
install.packages('stringr', repos="http://cran.us.r-project.org")
library(stringr)

```

Carregando a base de dados e observando os valores.


```{r}
df = read_excel("C:/Users/otavi/Documents/CAMG/Tabelas CAMG/Tabelas Finais CAMG/Nota_Todos_Anos.xlsx")
summary(df)

```


Calculando o Gini.

```{r}

gini= ineq(df$Nota_Final_Total , type = 'Gini')

print(gini)


```


```{r}
titulo = str_glue('O Índice de Gini do ICMS esportivo, de 2009 a 2018, é: {gini}')
plot(Lc(df$Nota_Final_Total), 
     main = "Distribuição dos Recursos do ICMS",
     xlab = titulo)

```

